### ISSUE TITLE
Bio pic icons need to be removed when an image is being used

### ISSUE THREAD

**Issue by Gchism94** [resbazaz/studyGroup#41]
The bios for Jaime Yazzie and Valeria Pfeifer have images and font awesome icons stacked. The font awesome icons need to be removed. 

Might be diagnosable after reviewing how this script works (?): https://github.com/resbazaz/studyGroup/blob/gh-pages/_includes/team.html

**Comment by Gchism94** [comment]
>Might be diagnosable after reviewing how this script works (?): https://github.com/resbazaz/studyGroup/blob/gh-pages/_includes/team.html 

Maybe not. I thought it could be from this chunk, but I can't see how it would do both? 
>28 `{% if member.headshot %}`
>29 `<img class="img-circle img-responsive" width="96" src="img/team/{{ member.headshot }}" alt="{{ member.name }}">`
>30 `{% endif %}`

**Comment by Aariq** [comment]
They only thing they seem to have in common is that they don't have github links.  Maybe commenting that out in the members.yml?  I don't know how to build the site locally to test it though.

**Comment by Gchism94** [comment]
Like this, I guess? - https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll

I'll play with it tomorrow or Friday.
